padding:
  cds:
    upstream: 0
    downstream: 0
segments:
  split_utrs: true
  include_utrs:
    five_prime: true
    three_prime: false
bed_formats:
  sambamba:
    columns:
      - "{chrom}"
      - "{start}"
      - "{end}"
      - "{coords}"
      - "0"
      - "{strand}"
      - "{gene};{transcript}"
      - "{gene_id}"
  data:
    columns:
      - "{chrom}"
      - "{start}"
      - "{end}"
      - "{gene_id}"
      - "{gene};{transcript}"
  exomedepth:
    columns:
      - "{chrom}"
      - "{start}"
      - "{end}"
      - "{gene}_{exon_number}"
  cnv:
    strip_chr_prefix: true
    columns:
      - "{chrom}"
      - "{start}"
      - "{end}"
      - "{gene};{transcript}"
